### ISSUE TITLE
User-feedback style changes

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#225]
Per user testing, incorporate the following style changes:

- [x] Type selector labels in the dataset pane should wrap when they're long
- [x] The header / toolbar icons duplicate functionality in a somewhat confusing way—care should be taken to make the function of each icon clear
- [x] The corner "next tip" buttons should be incorporated into the help bubbles
- [ ] <del>The lightbox holes should be outset, not inset (example: the matching interface)</del>(will be addressed by #368)
- [x] The matching interface buttons are heavily left-aligned, especially the visualization options.
- [x] Need better / more clear indicators for which vis options are required, and which can accept multiple fields
- [x] The redundant collapsing (icon + just clicking the widget header) is somewhat confusing
- [x] Checkmark in the OK icon is a little thin
- [x] Be consistent with text alignment in help bubbles
- [x] Choose a different color than blue for new next bubbles
- [x] Use the ! icon instead of the construction one in error screens
- [x] May be worth centering the buttons that swap datasets / visualizations
- [ ] <del>Legend for icons in matching view</del>(will be addressed by #205)
- [x] Make classic UI buttons and others (e.g. the dialog close button) more clearly clickable
- [x] The management dialog mixes buttons and non-button indicators... these should be clearly distinct
- [x] The copy link button is a little... obscure, even if it's in the right place.
- [x] Having the name of the vis option to the right of the icons hides the name a bit; it may make more sense on the left
- [x] The "n | n" fix to #214 still carries the "out of" connotation
- [ ] <del>Starting with a modal (where the main menu / help icons are visible but not clickable) is confusing</del>(will be addressed by #342)
- [ ] <del>Should the "Resonant Laboratory" app title be in the header (or just the intro modal that might go away anyway)?</del>(will be addressed by #342)
- [ ] <del>New users will probably start off with projects named "Untitled Project (31)"... for public scratch datasets, maybe it's best to rename the existing duplicate projects?</del>(will be addressed by #367)
- [ ] <del>It's not immediately clear that the data attributes in the matching interface come from the dataset; the relationships between the panes aren't obvious at first (should be part of the onboarding process)</del>(will be addressed by #205)
- [x] "Vis is working" shows up in the vis widget when required fields are missing (should go away with #138)... but a more accurate message should be added when we know what fields are required
- [x] The "infinity" label that indicates multiple fields can still run off the side
- [ ] <del>Small icon that indicates a private dataset looks kind of weird (misinterpreted by a couple users)</del>(wontfix unless it comes up again)
- [x] Add X button as well as OK to info/error modals
- [x] Panel transitions are too slow
- [ ] <del>Maybe support resizable panes</del>(wontfix)
- [x] "tips you haven't seen yet are blue"

**Comment by alex-r-bigelow** [comment]
More changes:
- Legend for icons in matching view
- Make classic UI buttons and others (e.g. the dialog close button) more clearly clickable
- The management dialog mixes buttons and non-button indicators... these should be clearly distinct

**Comment by alex-r-bigelow** [comment]
More changes:
- Panel transitions are too slow
- Maybe support resizable panes

**Comment by alex-r-bigelow** [comment]
- [ ] "tips you haven't seen yet are blue"
